<div id="live">
    <div class="page-header">
        <h1>
            Live stream
            <small>filtering: blah, blah, blah</small>
        </h1>
    </div>
    <div class="row">
        <div class="span8 offset2">
            <div class="well">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="span8 offset2">
            <div class="well">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="span8 offset2">
            <div class="well">
            </div>
        </div>
    </div>
</div>