
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Tweet Vote!!</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le styles -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <link href="/css/bootstrap.min.responsive.css" rel="stylesheet">
    <link href="/css/tw-vote-main.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="images/favicon.ico">
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="/">Tweet Vote!!</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="/">Home</a></li>
              <li><a href="/hall-of-fame">Hall of fame</a></li>
              <li><a href="/live">Live Stream</a></li>
              <li><a href="/about">About</a></li>
              <li><a href="/contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <?php echo $this->layout()->content; ?>
      
    </div> <!-- /container -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="span4">
                    <h4>Voting</h4>
                    <ul class="unstyled">
                        <li><a href="/hall-of-fame">Hall of fame</a></li>
                    </ul>
                </div>
                <div class="span4">
                    <h4>Company</h4>
                    <ul class="unstyled">
                        <li><a href="/about">About</a></li>
                    </ul>
                </div>
                <div class="span4">
                    <h4>Developers</h4>
                    <ul class="unstyled">
                        <li><a href="#">API</a></li>
                    </ul>                   
                </div>
            </div>
        </div>
        <div id="footer-floor">
            <div class="container">
             <div class="row">
                <div class="span2 offset10">
                    <p>Follow us <a href="#">@blah</a></p>
                </div>
                <div class="span4">
                    
                </div>
            </div>
            </div>
        </div>
    </footer>
    
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
    <script src="/js/bootstrap.min.js"></script>


  </body>
</html>



