<header id="overview" class="jumbotron subhead">
    <h1>About</h1>
    <p class="lead">behind the scenes...</p>
</header>

<section id="people">
    <div class="row">
        <div class="span4">
            <h3>John Doe</h3>
            <p>
               Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum blandit porttitor diam, ut tempus metus 
               vulputate a. Quisque eu nunc nulla, in posuere ipsum. Aenean at orci sed lacus condimentum consectetur. 
               In non dui sem. Morbi sit amet sapien nunc.
            </p>
        </div>
    </div>    
</section>